version: "3.9"

services:
  db:
    container_name: pg_pizza_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: pashckevich
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: iport234@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"